TRUNCATE TABLE
    "standard_difficulty_attributes",
    "taiko_difficulty_attributes",
    "catch_difficulty_attributes",
    "mania_difficulty_attributes";

-- AlterTable
ALTER TABLE "catch_difficulty_attributes"
ADD COLUMN "cs" DOUBLE PRECISION NOT NULL,
ADD COLUMN "ar" DOUBLE PRECISION NOT NULL,
ADD COLUMN "od" DOUBLE PRECISION NOT NULL,
ADD COLUMN "hp" DOUBLE PRECISION NOT NULL,
ADD COLUMN "clock_rate" DOUBLE PRECISION NOT NULL;

-- AlterTable
ALTER TABLE "mania_difficulty_attributes"
ADD COLUMN "cs" DOUBLE PRECISION NOT NULL,
ADD COLUMN "ar" DOUBLE PRECISION NOT NULL,
ADD COLUMN "od" DOUBLE PRECISION NOT NULL,
ADD COLUMN "hp" DOUBLE PRECISION NOT NULL,
ADD COLUMN "clock_rate" DOUBLE PRECISION NOT NULL;

-- AlterTable
ALTER TABLE "standard_difficulty_attributes"
ADD COLUMN "cs" DOUBLE PRECISION NOT NULL,
ADD COLUMN "ar" DOUBLE PRECISION NOT NULL,
ADD COLUMN "od" DOUBLE PRECISION NOT NULL,
ADD COLUMN "hp" DOUBLE PRECISION NOT NULL,
ADD COLUMN "clock_rate" DOUBLE PRECISION NOT NULL;

-- AlterTable
ALTER TABLE "taiko_difficulty_attributes"
ADD COLUMN "cs" DOUBLE PRECISION NOT NULL,
ADD COLUMN "ar" DOUBLE PRECISION NOT NULL,
ADD COLUMN "od" DOUBLE PRECISION NOT NULL,
ADD COLUMN "hp" DOUBLE PRECISION NOT NULL,
ADD COLUMN "clock_rate" DOUBLE PRECISION NOT NULL;